# Generated by Django 6.1.1 on 2026-09-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='next_issue_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
